### ISSUE TITLE
torch.set_num_threads equal to 1 leads to use all cpu cores

### ISSUE THREAD

**Issue by hal-314** [bytedeco/javacpp-presets#1152]
Hello

First, thanks for this great bindings! 

Currently, I'm using to run a Pytorch Model on a server. As it has several threads to serve users simultaneously, I want to limit threads used by Pytorch. When calling `torch.set_num_threads(1)` leads to a 100% CPU usage and a very slow inference **only** using a model loaded with torch jit. Setting to any other value works fine. In Python, it works.

# Setup
JavaCPP-Presets: 1.5.7
Pytorch: 1.10.2 (artifact downloaded from JavaCPP-Preset maven repository)
Device: on CPU
Model: a classifier loaded with `torch.jit.load`

# Example
Add `set_num_threads(1) in line 12 of `ExampleApp.java`.

This behaviour doesn't happen in `SimpleMNIST.java`  or when defining a network with Java bindings. It only appears with when loading a model through `torch.jit.load`.

**Comment by saudet** [comment]
It's possible this is OpenBLAS, try to set the OMP_NUM_THREADS environment variable, among others.

**Comment by saudet** [comment]
Looks like there are couple more functions that you'll need to call to set the number of threads for everything:
https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html

**Comment by hal-314** [comment]
Thanks. I set OMP_NUM_THREADS  and MKL_NUM_THREADS to 1 and it worked. I was using `torch.set_num_threads` as said in  https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html but it didn't work when setting to 1. Any other value was fine. In Python they work just fine. So, it maybe something related to the java binding. 

I close the issue as setting environment variables is a valid workaround. Thank you

**Comment by saudet** [comment]
I see, PyTorch isn't able to set the number of threads for OpenBLAS, but it is able to set it for MKL, which is what their builds get linked with. Anyway, there is a way to set the number of threads with the presets for OpenBLAS, and it also works when linked with MKL at runtime. Please try to call [org.bytedeco.openblas.presets.openblas_nolapack.blas_set_num_threads()](http://bytedeco.org/javacpp-presets/openblas/apidocs/org/bytedeco/openblas/presets/openblas_nolapack.html#blas_set_num_threads-int-) instead of setting environment variables. Let me know if it doesn't work for some reason though. Thanks!
