### ISSUE TITLE
JavaCPP doesnt recognize C++ "struct alignas(16) Pixel"

### ISSUE THREAD

**Issue by eix128** [bytedeco/javacpp-presets#1168]
JavaCPP doesnt recognize

	// pixel
	struct alignas(16) Pixel
	{
		UNIGINE_INLINE Pixel() {}
		UNIGINE_INLINE Pixel(int r, int g = 0, int b = 0, int a = 0)
		{
			i.r = r;
			i.g = g;
			i.b = b;
			i.a = a;
		}
		UNIGINE_INLINE Pixel(float r, float g = 0.0f, float b = 0.0f, float a = 0.0f)
		{
			f.r = r;
			f.g = g;
			f.b = b;
			f.a = a;
		}
		union
		{
			Pixeli i;
			Pixelf f;
		};
	};

ITs more standard way to align
check out on stackoverflow:

https://stackoverflow.com/questions/19958912/what-is-the-difference-between-struct-declspecalign16-sse-t-and-struct-ali

**Comment by saudet** [comment]
We can work around that by considering it as an attribute and providing the right Info this way:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#ignoring-attributes-and-macros
But, you're right, since this is actually a keyword, it should be ignored by default. I've updated that in commit https://github.com/bytedeco/javacpp/commit/8c34ccbb726de90e61b30074850d9055ca4ec6a5. Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment]
The fix for this has been released with JavaCPP 1.5.8. Thanks for reporting!
