### ISSUE TITLE
install pytorch module with gpu extension error

### ISSUE THREAD

**Issue by oOTWK** [bytedeco/javacpp-presets#1238]
I want to install pytorch with gpu extension
`mvn install --projects pytorch -Djavacpp.platform=linux-x86_64 -Djavacpp.platform.extension=-gpu`
but it requires dependencies also with "-gpu".
In other words, it requries `javacpp-1.5.7-linux-x86_64-gpu.jar`, `cpython-3.10.2-1.5.7-linux-x86_64-gpu.jar`, `openblas-0.3.19-1.5.7-linux-x86_64-gpu.jar`, and `numpy-1.22.2-1.5.7-linux-x86_64-gpu.jar`. However, these dependencies have no effect with gpu extension and no such jars are existed. To work around this, I just renamed those dependency jars by adding "-gpu".

**Comment by saudet** [comment]
That sounds like a bug in your version of Maven. Please make sure you're using the latest version.

**Comment by oOTWK** [comment]
I'm using maven 3.8.6 which is the latest. I will check pom.xml.

**Comment by saudet** [comment]
Ok, does this also happen with Maven 3.6.3? Or only with 3.8.x?

**Comment by oOTWK** [comment]
I just tried with 3.6.3 and it works fine. So the problem is with version 3.8.6.
Thank you!

**Comment by HGuillemet** [comment]
The problem arose with 3.8.5.
3.8.4 works fine too.

**Comment by saudet** [comment]
And they didn't fix it in 3.8.6? Sigh... Someone should probably report this upstream: https://issues.apache.org/jira/browse/MNG

**Comment by HGuillemet** [comment]
Some presets like pytorch declare a dependency in their pom to a `-platform` artifact (numpy in the case of pytorch).

The platform artifacts, in their own pom, declare dependencies towards each native artifact using classifiers `${javacpp.platform.linux-x86_64}` and similar. The `javacpp.platform.*` properties contain the contatenation `${javacpp.platform}${javacpp.platform.extension}`.
So if an extension is active (e.g. we are trying to build a GPU-enabled pytorch), it will record a dependency towards the native jars with the extension. In our case, towards numpy with classifier `linux-x86_64-gpu`. But such artifact doesn't exist and the build fails.

For an unknown reason I didn't dig further, probably related to how user properties and system properties interact, in Maven versions up to 3.8.4, the `javacpp.platform.extension` is dropped before the dependencies of the platform artifact are evaluated and the build passes.

I think the new behavior is the good one: if we are building with GPU enabled, and if the dependency also supports GPU, we should use this version. But if the dependency doesn't support a GPU build, it shouldn't fail either.

A good way to fix this (and should also help in other situations) would be to arrange so that we depend on native artifacts with classifiers `${javacpp.platform}${javacpp.platform.effective-extension}`. Where `javacpp.platform.effective-extension` is computed from `${javacpp.platform.extension}` and a list of supported extensions defined in the platform pom:

```
<properties>
 <javacpp.supported-extensions>-gpu -python -python-gpu</javacpp.supported.extensions>
</properties>
```
`javacpp.platform.effective-extension` should be set to `${javacpp.platform.extension}` if it's in the list, and emptied if not.
This computation probably would need a specific goal in the javacpp plugin, unless we can work out some trick, maybe with the regex goal of build helper plugin.

Any better idea ?

**Comment by saudet** [comment]
System properties are not supposed to be able to influence the properties of dependencies, that's by design. That's a new bug in Maven, and they will need to fix it someway somehow.

**Comment by HGuillemet** [comment]
`javacpp.platform` affects the dependencies. Why `javacpp.platform.extension` should not ?

**Comment by saudet** [comment]
It does, it uses profiles, but using profiles like that isn't recommended by Maven. There's no reason they would intentionally add more features that would allow to mess around with dependencies like that, so it's a bug!

**Comment by HGuillemet** [comment]
You have always been able to do thinks like:
```
<dependency>
 <groupId>org.bytedeco></groupId>
 <artifactId>${dep}</artifactId>
 <version>1.0</version>
</dependency>
```
And `mvn -Ddep=x` works, even if this dependency is declared in a dependency of the project being built, with both 3.8.4.and 3.8.6, without using any profile.

Presently, if you do `mvn -pl pytorch install -Djavacpp.platform=linux-x86_64`, your build will depend on linux implementation of numpy, one of pytorch dependencies.
If you do  `mvn -pl pytorch install -Djavacpp.platform=linux-x86_64 -Djavacpp.platform.extension=-gpu`, the build will look for gpu implementation of numpy with maven 3.8.6, and for  generic linux implementation with maven 3.8.4.

Independently of maven way to work, and of whether numpy has a gpu implementation or not, which behavior is the desired one ?

**Comment by saudet** [comment]
> And `mvn -Ddep=x` works, even if this dependency is declared in a dependency of the project being built, with both 3.8.4.and 3.8.6, without using any profile.

No, it won't work. Try it!

**Comment by saudet** [comment]
> Independently of maven way to work, and of whether numpy has a gpu implementation or not, which behavior is the desired one ?

We need a way to modify transitive dependencies, like we can sort of do with Gradle with a lot hacking: 
https://github.com/bytedeco/gradle-javacpp#the-platform-plugin

But there is no way to do that at all with plugins in Maven, see issue #846.

Unless you consider this new Maven bug as a "feature", in which case we should get the Maven team to confirm that this is indeed a new "feature", so that they will maintain support of this new "feature" for all new versions. Could you do that?

**Comment by HGuillemet** [comment]
> No, it won't work. Try it!

I did:
Project a:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>test</groupId>
  <artifactId>a</artifactId>
  <version>1.0</version>
  <name>Project A</name>

  <dependencies>
   <dependency>
    <groupId>test</groupId>
    <artifactId>b</artifactId>
    <version>1.0</version>
   </dependency>
  </dependencies>

</project>
```
Project b:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>test</groupId>
  <artifactId>b</artifactId>
  <version>1.0</version>
  <name>Project B</name>

  <dependencies>
   <dependency>
    <groupId>test</groupId>
    <artifactId>${dep}</artifactId>
    <version>1.0</version>
   </dependency>
  </dependencies>

</project>
```
Project c:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>test</groupId>
  <artifactId>c</artifactId>
  <version>1.0</version>
  <name>Project C</name>

</project>
```
```shell
cd c
mvn install

cd ../b
mvn -Ddep=c install

cd ../a
mvn -Ddep=c package
mvn -Ddep=x package
```

**Comment by saudet** [comment]
Like I said, if that works, it's a bug. If it works with Maven 3.8.4, that's a bug in Maven 3.8.4. Whatever version this works with, it's a bug in that version. Note that I cannot reproduce this myself with Maven 3.8.4, so I'm not sure why that works for you. In any case, please report upstream. If they confirm that this is a new feature, then that's fine. But until this is confirmed as working correctly, this is not how Maven should be working according to its design, so until those design docs changes, this is a bug!

**Comment by HGuillemet** [comment]
> Note that I cannot reproduce this myself with Maven 3.8.4,

That's quite strange. I tried 3.6.3, 3.8.4, 3.8.6.
For any version, `mvn -Ddep=x package` emits an `test:x:jar:1.0 missing` error, while `mvn -Ddep=c package` works.
What do you get your side ?

**Comment by saudet** [comment]
I see, you're not setting the default value of "dep" to anything, so yes it's probably falling back on system properties in that case. How do you want to make anything useful out of that though?

**Comment by HGuillemet** [comment]
Good point. So now if I replace project b with:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>test</groupId>
  <artifactId>b</artifactId>
  <version>1.0</version>
  <name>Project B</name>

  <properties>
   <dep>c</dep>
  </properties>

  <dependencies>
   <dependency>
    <groupId>test</groupId>
    <artifactId>${dep}</artifactId>
    <version>1.0</version>
   </dependency>
  </dependencies>

</project>
```
Then, on project a, with 3.8.4 `mvn -Ddep=x package` works (`-D` is ignored), but with 3.8.6 it does not (`-D` takes priority over the default).
> How do you want to make anything useful out of that though?

At least now we have a test case, and I can go upstream and query if it's a bug or feature.

**Comment by HGuillemet** [comment]
[MNG-7563](https://issues.apache.org/jira/browse/MNG-7563)

**Comment by HGuillemet** [comment]
Things have moved. The maven team will revert the breaking change for now. So version 3.8.4 and 3.8.7+ should work,  3.8.5 and 3.8.6 should be avoided for JavaCPP presets.
However, Maven 4 will probably break again the processing of extensions. We will have to adapt or move to Gradle. No hurry though.

**Comment by HGuillemet** [comment]
Maven 3.8.7 is out.
This issue can be closed.
