### ISSUE TITLE
[pytorch] I found why javacpp is stuckandlocked in idea and vscode ,because of the torch.class 5w lines? to large

### ISSUE THREAD

**Issue by mullerhai** [bytedeco/javacpp-presets#1291]
Hi ,
     I have try so  many times ,in multiple pc  and macbook, and  work with idea or vscode, the javacpp all stuckandlocked  can not solved, then I found ,because of  when write the function from  [org.bytedeco.pytorch.global.torch], the idea with search more time  and  with stuckandlocked, then found this class will load one minute with it's 5w lines, it is too large ,please could we  split it into multiple java file ?

**Comment by saudet** [comment]
I've just tried with IntelliJ, NetBeans, and Visual Studio Code, but I'm not having any slowness issues with any of them loading the sample project at https://github.com/bytedeco/javacpp-presets/tree/master/pytorch/samples and writing code using functions from org.bytedeco.pytorch.global.torch. The problem is probably caused by other plugins you may be using.

**Comment by HGuillemet** [comment]
I'm using IDEA, and indeed decompiling and displaying torch.class (after typing Ctrl-B on a torch identifier for instance) may be a bit slow. Never more than a few seconds though, and if it gets stuck, try to increase the memory allocated to IDEA (Help menu / Change memory settings). 
Also IDEA decompiles torch.class instead of directly reading the source from the source jar because of some size limit than you can change with this custom property (From Help Menu/Edit Custom Property):
```
idea.max.intellisense.filesize=4096
```

**Comment by mullerhai** [comment]
> idea.max.intellisense.filesize=4096

perfect ,Now it is can normally open and write the code,thanks

**Comment by mullerhai** [comment]
> I've just tried with IntelliJ, NetBeans, and Visual Studio Code, but I'm not having any slowness issues with any of them loading the sample project at https://github.com/bytedeco/javacpp-presets/tree/master/pytorch/samples and writing code using functions from org.bytedeco.pytorch.global.torch. The problem is probably caused by other plugins you may be using.

not the plugin effect ,it is something about idea setting,Now it is solved,thanks
