### ISSUE TITLE
make native builds part of maven build?

### ISSUE THREAD

**Issue by jjYBdx4IL** [bytedeco/javacpp-presets#170]
See https://github.com/jjYBdx4IL/javacpp-presets/blob/pulldown/opencv/pom.xml

I'm using maven-download-plugin for downloads there (it caches the downloads inside the user's local maven repo) and the maven antrun plugin to run the cppbuild.sh script. That way we could also declare versions centrally in the javacpp-presets pom.xml and feed them to the scripts.

**Comment by saudet** [comment]
That's a nice idea :) A couple of things though. We don't need maven-download-plugin because cppbuild.sh already does caching and everything we need. Also, would it be possible to move the maven-antrun-plugin to the parent pom.xml file as part of the pluginManagement element? And I think we should bind the execution to "generate-resources", which makes more sense than "generate-sources", what do you think? And I'm pretty sure we'll need to explicitly run "bash" on Windows for this to work. If that makes sense, and can make the necessary modifications, send a pull request and I'll merge this in! Thanks

**Comment by saudet** [comment]
Merged from #175, thanks for the contribution!

**Comment by saudet** [comment]
Included in the release of version 1.2. Again, thanks for the contribution!

BTW, I would be very interested if you could continue your work to turn all the samples of all the presets into tests for surefire or failsafe...
