### ISSUE TITLE
Seems no preset for opencv_contrib module with opencv3

### ISSUE THREAD

**Issue by strgrb** [bytedeco/javacpp-presets#319]
opencv_contrib is in another repository for opencv3, and is missing in the opencv preset

**Comment by saudet** [comment]
Yes, it's another repository with more modules. Which one are you interested in?

**Comment by strgrb** [comment]
maybe face and tracking

**Comment by saudet** [comment]
Here's face:
https://github.com/bytedeco/javacpp-presets/blob/master/opencv/src/main/java/org/bytedeco/javacpp/opencv_face.java
Someone will need to do the same for tracking...

**Comment by strgrb** [comment]
I would like to do it but maybe I need some guide, because I'm not so familiar with javacpp

**Comment by saudet** [comment]
Try to create `presets/opencv_tracking.java` based on `presets/opencv_face.java` and just rebuild from source with Maven: https://github.com/bytedeco/javacpp-presets/#build-instructions

**Comment by strgrb** [comment]
thank you, I'll try it later.

**Comment by beligum** [comment]
[offtopic: I hope I'm not thread stealing here, but it makes sense to not start a new one..]

I recently discovered opencv has it's own text detection features now (I'm not talking about OCR, this is about the step before eg. tesseract): http://docs.opencv.org/3.1.0/da/d56/group__text__detect.html

These couple of functions are the ideal match to the Tesseract (and others) modules since they allow us to pull text from any image or frame.

Any chance there's a JavaCPP preset already for opencv text anywhere?

**Comment by beligum** [comment]
Started working on this in a new topic, see #327 .

**Comment by saudet** [comment]
Ok, it's done! Check the commit above, and try it out with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment]
The `aruco`, `bgsegm`, `img_hash`, `phase_unwrapping`, `plot`, `structured_light`, `tracking`, and `xphoto` modules are now included as of the release of version 1.4.1. Enjoy!
