### ISSUE TITLE
Tesseract fails on MacOS

### ISSUE THREAD

**Issue by tomfisher** [bytedeco/javacpp-presets#46]
I tried to build an eclipse project by ``` mvn eclipse:eclipse -Dplatform.dependencies=true``` and then run the sample code tesseract code on MacOS from Eclipse with the error "Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnitesseract in java.library.path"

I checked the dependencies and all platform jars are in the classpath.  Then I tried to run the sample code using ```mvn package exec:java -Dexec.mainClass=BasicExample -Dexec.args="/open/tesseract-ocr/testing/phototest.tif" -Dplatform.dependencies=true```, got the above error with no luck.

**Comment by saudet** [comment]
Could you call [Loader.getPlatform()](http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/Loader.html#getPlatform--) and let me know what that returns? Thanks

**Comment by tomfisher** [comment]
It returns macosx-x86_64.

I also did trace the call, everything looks fine.

**Comment by saudet** [comment]
Ok, and which version  of JavaCPP are you using?

**Comment by tomfisher** [comment]
This is my pom.xml:

```

	<dependencies>
		<dependency>
			<groupId>org.bytedeco.javacpp-presets</groupId>
			<artifactId>opencv</artifactId>
			<version>2.4.11-0.11</version>
		</dependency>
		<dependency>
			<groupId>org.bytedeco.javacpp-presets</groupId>
			<artifactId>tesseract</artifactId>
			<version>3.03-rc1-0.11</version>
		</dependency>
		<dependency>
			<groupId>org.bytedeco.javacpp-presets</groupId>
			<artifactId>ffmpeg</artifactId>
			<version>2.6.1-0.11</version>
		</dependency>
	</dependencies>

```

**Comment by tomfisher** [comment]
The resolved cpp version is 0.11

**Comment by saudet** [comment]
I've just tried it again, and it works just fine here. Could you copy/paste the whole stack trace of the exception?

**Comment by tomfisher** [comment]
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnitesseract in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1119)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:536)
	at org.bytedeco.javacpp.Loader.load(Loader.java:411)
	at org.bytedeco.javacpp.Loader.load(Loader.java:354)
	at org.bytedeco.javacpp.tesseract.<clinit>(tesseract.java:12)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:386)
	at org.bytedeco.javacpp.Loader.load(Loader.java:354)
	at org.bytedeco.javacpp.tesseract$TessBaseAPI.<clinit>(tesseract.java:3422)
	at io.yark.core.presets.demo.BasicExample.main(BasicExample.java:12)
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/94/2lbtjlws29zfr_jq0ljn3cnc0000gn/T/javacpp35309413919615/libjnitesseract.dylib: dlopen(/private/var/folders/94/2lbtjlws29zfr_jq0ljn3cnc0000gn/T/javacpp35309413919615/libjnitesseract.dylib, 1): Library not loaded: /Users/saudet/projects/bytedeco/javacpp-presets/tesseract/cppbuild/macosx-x86_64/lib/libtesseract.3.dylib
  Referenced from: /private/var/folders/94/2lbtjlws29zfr_jq0ljn3cnc0000gn/T/javacpp35309413919615/libjnitesseract.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1814)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1083)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:525)
	... 9 more
```

I think this may caused by the dependent libs e.g. tiff are not installed in my system. If the memory serves me right, there were a couple of preloading libs when I traced why it could not load the library yesterday. I just brew install tesseract WITHOUT the --without-libtiff option and everything works fine now.

**Comment by saudet** [comment]
I believe I've found the problem, so check out the latest commit and let me know if you still have problems with that one. This will only have an effect if you package the `dylib` files in JAR files. If you install the `dylib` on the system with Homebrew or something, that will work without the patch as you found out. Thanks for reporting and for testing this out!

**Comment by tomfisher** [comment]
It works now. Thanks.

**Comment by FloWi** [comment]
@saudet, thanks for providing a patch. Would you mind explaining on how to apply it? I need a little guide on how to build the whole project with the patch applied. I guess you guys have already documented it - so a link would be fine.

**Comment by saudet** [comment]
@FloWi Instructions are here: https://github.com/bytedeco/javacpp-presets/#build-instructions
It's usually just two commands:
```bash
$ bash cppbuild.sh install
$ mvn install
```

**Comment by FloWi** [comment]
Hi Samuel!

Thanks a lot for your help! 

I tried it at work with an openSUSE box, but ran on several errors due to missing packages on my machine necessary for compiling. 

Do you have a list of packages at hand that are being needed for building javacpp? 

I got it to the point where the flyCapture-build is failing with this error. 

https://gist.github.com/FloWi/72babed51136921203dd

**Comment by saudet** [comment]
I've added a couple of dependencies to the JAR files that were missing from Ubuntu, but I didn't check what we might need to bundle extra for openSUSE. In any case, most of the requests I get are for CentOS, and that pretty comes with nothing at all. And we also need someone to set up CI: https://github.com/bytedeco/javacpp-presets/issues/22
Would that be something you would like to work on?

FlyCapture is going to fail if we don't install it beforehand. It's not open source, and we need to go through a website to download the library, so that's pretty normal. I guess I'll make `cppbuild.sh install` exit at that point just to make sure users see the error message. Thanks for the feedback!

**Comment by FloWi** [comment]
Yeah, CI would be awesome for your cool project. I can take a look at the travis integration next week. This week, my nerd-time is very limited, due to real-life constraints ;-) At work we have a jenkins running monitoring our git-repos. So I know a bit about it I didn't set it up. Perhaps I can motivate my admin-buddy to help getting me started. 

I did a quick check on travis and saw, that they even support mac-builds - but unfortunately they are at capacity with their mac-environment. How do you currently handle the build of new releases? Is it possible to build a mac or windows release on a linux-box? 

So, I'm willing to help but don't like to make promises I can't keep. So, if anyone else has first hand experience with travis-ci and maven-builds I can't compete with that. 

Good idea to provide better information on FlyCapture to the user. 

Best, 
Florian

**Comment by saudet** [comment]
Right now, I just build everything here manually on my machines. It takes a while to build everything from scratch, so it's not going to scale, but I do what I can with what I have for now...

In any case, thanks for your interest! It would be great to get some help. Let me know if you need anything from me to get started! And BTW if you find a way to attract some money to this project, it might also be possible to hire someone else to work on it too...

**Comment by jiwhiz** [comment]
I got the same error again. Is that because the `leptonica-1.72-macosx.patch` not updated for Leptonica-1.72?

Thanks.

**Comment by saudet** [comment]
@jiwhiz I've tried it again just to make sure, and version 1.0 works fine here. Could you copy/paste the whole stack trace that you get? Thanks!

**Comment by jiwhiz** [comment]
Sorry, my mistake. I was testing [BasicTesseractExample](https://github.com/piersy/BasicTesseractExample), and it is using `3.03-rc1-0.11`. After I changed to `3.03-rc1-1.0`, it is working now. Thanks a lot!

**Comment by DanielHit** [comment]
i have meet the same problem and change to 1.0. it work fine now. Thanks!

**Comment by saudet** [comment]
@Kumaran50 You'll need to add a dependency on "tesseract-platform", not just "tesseract".
