### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jnilept in java.library.path

### ISSUE THREAD

**Issue by wissil** [bytedeco/javacpp-presets#654]
I tried to create a sample Maven project like the one from the home page of this project with only one Maven dependency. The project is [this one](https://github.com/piersy/BasicTesseractExample).

Maven dependency that I used is:

`
		<dependency>
			<groupId>org.bytedeco.javacpp-presets</groupId>
			<artifactId>tesseract</artifactId>
			<version>4.0.0-rc2-1.4.3</version>
		</dependency>
`

However, I am getting the following error.

`java.lang.UnsatisfiedLinkError: no jnilept in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)`

`Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/yd/t0g1m0993f7g6lyhd9dkzj99sq81w6/T/javacpp921625607548161/libjnilept.dylib: dlopen(/private/var/folders/yd/t0g1m0993f7g6lyhd9dkzj99sq81w6/T/javacpp921625607548161/libjnilept.dylib, 1): Library not loaded: /Users/saudet/projects/bytedeco/javacpp-presets/leptonica/cppbuild/macosx-x86_64/lib/liblept.4.dylib
  Referenced from: /private/var/folders/yd/t0g1m0993f7g6lyhd9dkzj99sq81w6/T/javacpp921625607548161/libjnilept.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)`

The command that I ran was simply `mvn clean install` on Mac OS.
Is there something that I'm doing wrong?

**Comment by saudet** [comment]
Use "tesseract-platform", not "tesseract", unless you also add the
artifacts for your platform.

**Comment by Arpana-786** [comment]
hi, same issue is coming to java.lang.UnsatisfiedLinkError: no jnilept in java.library.path, I am using intellij when i run it on local it is working perfect , but I am making service where I have to use tessrec ,  when i run it on hdfs because my images and tessdata on hdfs and I want to run this service on hdfs. so when I am giving spark submit command for running command " spark-submit --packages com.databricks:spark-xml_2.12:0.9.0,net.sourceforge.tess4j:tess4j:4.5.4,org.bytedeco.javacpp-presets:tesseract-platform:4.0.0-1.4.4,org.bytedeco.javacpp-presets:leptonica:1.77.0-1.4.4,org.bytedeco.javacpp-presets:leptonica:1.77.0-1.4.4,org.bytedeco.javacpp-presets:tesseract:4.0.0-1.4.4,net.java.dev.jna:jna:5.6.0 --class Image --master spark://prod5:7077 --driver-memory 32g  --executor-memory 32g --total-executor-cores 20 /pafilescrapper/HDFS_Backup/Arpana/Arpana/feed_validation_2.12-0.1.jar)

and I am getting an error Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnilept in java.library.path Please help me out I am just beginner.

**Comment by saudet** [comment]
@Arpana-786 Please upgrade to a more recent version.
