### ISSUE TITLE
ffmpeg build on macOS Catalina produces invalid binaries

### ISSUE THREAD

**Issue by b005t3r** [bytedeco/javacpp-presets#815]
I just built ffmpeg from source (version 1.5) on macOS Catalina and after running the command line tool with dylibs created, I get: `Segmentation fault: 11`.

Looks like a known issues, but I'm not sure if you fixed it already: https://forums.developer.apple.com/thread/121887

> add -fno-stack-check to CFLAGS/CXXFLAGS
or
> set MACOSX_DEPLOYMENT_TARGET=10.14 in the environment or choose 10.14 as deployment target in Xcode

I haven't tested these workarounds yet, however.

**Comment by b005t3r** [comment]
Setting `MACOSX_DEPLOYMENT_TARGET=10.14` resolves the issue. Didn't try the other one.

**Comment by saudet** [comment]
That looks like an issue with Xcode 11 that they are most likely going to fix eventually...
Another answer to this question could be to use Xcode 10 or less for the moment.

Anyway, please do send a pull request with your modifications so that they get integrated!
This way you wouldn't need to do custom builds all the time.
