### ISSUE TITLE
Presets for Bullet Phyics SDK 

### ISSUE THREAD

**Issue by breandan** [bytedeco/javacpp-presets#828]
Would be nice to call Bullet from the JVM: https://github.com/bulletphysics/bullet3

**Comment by saudet** [comment]
If you have some time to give it a try, please do! It does take getting used to tinkering with the header files, but I'll be here to help.

**Comment by dustContributor** [comment]
Having a 3D physics engine in Java would be pretty nice. The current options are:

jBullet -> Very, very outdated and incomplete.
libGDX Bullet bindings -> They work but they bring a lot of libGDX idioms with it (for instance, they replace all and every vector/matrix object usage with their own thread-hostile implementations, same with some thread-hostile reference tracking they do, overall a very poor experience, you can't even call "new btRigidBody()" from two separate threads safely).

And that's about it. It'd be nice to have bindings for either a recent version of Bullet, or maybe PhysX since it got MIT'd by Nvidia some time ago.

 Performance oriented bindings would be nice. For instance, what LWJGL does, where if you have a function like:

`btRigidBody::setVelocity(btVector3)`

The equivalent Java binding is capable of receiving a flat long like:

`body.setVelocity(long address)`

This enables certain usages with direct/off-heap buffers so HotSpot can easily do escape analysis on them:

```java
try(NativeBuffer vel = nativeAllocator.alloc(3 * SIZEOF_FLOAT)) {
  vel.put(1.0f).put(1.0f).put(0.0f).flip();
  /* 
  * vel object will probably be stack allocated given 
  * only the inner long address is used, reducing GC pressure.
  */
  body.setVelocity(nativeAlloc.address());
}
```

That's pretty much what you have going with the PointerVector example in the readme of the main repo.

Otherwise if forcing the usage of a btVector3 object (sort of like what libGDX bindings do with their Vector3 objects), that gets passed to the native JNI glue function, this happens:

```java
var vel  = new btVector3(1,1,0);
// vel 'escapes' into native call, always gets heap allocated, increasing GC pressure
body.setVelocity(vel);
```

Anyway, just chiming in.

**Comment by calvertdw** [comment]
This would be nice. Me or someone from my team might try this soon. For now I just wanted to summarize the current alternatives and why JavaCPP could probably be better.

There is https://github.com/libgdx/libgdx/tree/master/extensions/gdx-bullet
but unfortunately, it wraps an aging version 2.87, which is from 2017.

There is https://github.com/stephengold/Libbulletjme
but unfortunately it is providing many opinions on top of Bullet, so the Bullet documentation is not the primary source. It does not wrap the Bullet API directly, but it does use an up to date version of Bullet. (Jan 2022).

jbullet wraps an even older version 2.72 [****](http://jbullet.advel.cz/) This was last release in 2010. (12 years ago!)

**Comment by saudet** [comment]
@breandan @calvertdw Thanks to @mode89 we now have presets for Bullet Physics SDK!
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by calvertdw** [comment]
I thought you guys might like to see a video showing example simulations based on this preset. Thanks again!

https://www.youtube.com/watch?v=eC8_mBwpECQ

**Comment by mode89** [comment]
Thank you @calvertdw for your efforts in testing it :)
